name: Lint and Test Upon Push
run-name: Linting and Testing ${{ github.ref_name }}
on: [push]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Lint Codebase
        run: bun run lint
      - name: Run Test
        run: bun run test:ci
