name: Lint and Test Upon Push
run-name: Linting and Testing ${{ github.ref_name }}
on: [push]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint codebase
        run: bun run lint
      - name: Run tests
        run: bun run test:ci
      - name: Report test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: test-results
          path: reports/jest.xml
          reporter: jest-junit
